title: Henry Andrés Cortés
description: Computational Materials Scientist | Battery Modeling
logo: /assets/img/Cortes.jpg
theme: jekyll-theme-minimal

email: hacortes@bcamath.org
github_username: hacortesp

show_downloads: false
