title: Henry Andrés Cortés Páez
description: >
  Postdoctoral Researcher in Computational Materials Science and Battery Modeling.
logo: /assets/img/Cortes.jpg
theme: jekyll-theme-minimal

email: hacortes@bcamath.org
github_username: hacortesp

show_downloads: false
google_analytics:
