project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  reader-mode: false
  title: "Henry A. Cortes"
  favicon: webpage_logo.png
  site-url: "https://matiasandina.netlify.app"
  repo-url: "https://github.com/hacortesp/WebSite/"
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card:
    creator: "Henry Andres Cortes"
    card-style: summary_large_image
  
  search:
    location: navbar
    type: overlay
    copy-button: true
    
  comments:
    utterances:
      repo: matiasandina/Webpage
      label: "Comment"
      theme: github-dark

  #page-footer:
    # using footer in _metadata
    #right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    #left: "&copy; CC-By Matias Andina, 2023"
  
  navbar: 
    background: secondary
    search: true
    left:
      - text: "Research Areas"
        file: research/index.qmd
      - href: publications/index.qmd
      - href: codes/index.qmd
        text: Software
      - text: "CV"
        href: files/CV.pdf
      #- text: "Past lives"
      #  file: past_lives/index.qmd
    right: 
      - icon: github
        href: https://github.com/hacortesp
      - icon: envelope
        href: mailto:hacortesp@bamath.gro
      - text: "{{< ai orcid >}}" 
        href: https://orcid.org/my-orcid?orcid=0000-0002-2361-5193
      - text: "{{< ai google-scholar >}}"
        href: https://scholar.google.de/citations?hl=en&pli=1&user=Yqqj8fEAAAAJ
      - icon: linkedin
        href: https://www.linkedin.com/in/henry-andres-cortes-paez-72309a76/


format:
  html:  
    theme:
      light: [flatly, theme.scss] 
      dark: [darkly, dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
    # page formatting
    grid:
      #sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
editor: visual
